// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthor = "authors"

// Author mapped from table <authors>
type Author struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NAME    string `gorm:"column:NAME;not null" json:"NAME"`
	Country string `gorm:"column:country;not null" json:"country"`
	Age     int32  `gorm:"column:age;not null" json:"age"`
}

// TableName Author's table name
func (*Author) TableName() string {
	return TableNameAuthor
}
